namespace InPlayWiseData.Entities
{
    public class InputData
    {
        public float home_score { get; set; }
        public float home_shots_on_target { get; set; }
        public float home_shots_off_target { get; set; }
        public float home_attacks { get; set; }
        public float home_dangerous_attacks { get; set; }
        public float home_corners { get; set; }
        public float home_penalties_awarded { get; set; }
        public float home_possession { get; set; }
        public float away_score { get; set; }
        public float away_shots_on_target { get; set; }
        public float away_shots_off_target { get; set; }
        public float away_attacks { get; set; }
        public float away_dangerous_attacks { get; set; }
        public float away_corners { get; set; }
        public float away_penalties_awarded { get; set; }
        public float away_possession { get; set; }
        public string match_info { get; set; }
        public float match_minute { get; set; }
        public string live_match_id { get; set; }
        public float total_score { get; set; }
        public string scored_in_remaining_t { get; set; }
        public float time_from_last_goal { get; set; }
        public float time_from_last_goal_home { get; set; }
        public float time_from_last_goal_away { get; set; }
        public float cp_goal_first_10m { get; set; }
        public float total_shots_on_off_ratio { get; set; }
        public float home_shots_on_off_ratio { get; set; }
        public float away_shots_on_off_ratio { get; set; }
        public float total_attacks_ratio { get; set; }
        public float home_attacks_ratio { get; set; }
        public float away_attacks_ratio { get; set; }
        public float total_corners_ratio { get; set; }
        public float home_corners_ratio { get; set; }
        public float away_corners_ratio { get; set; }
        public float total_penalties_ratio { get; set; }
        public float home_penalties_ratio { get; set; }
        public float away_penalties_ratio { get; set; }
        public float avg_time_to_goal { get; set; }
        public float home_avg_time_to_goal { get; set; }
        public float away_avg_time_to_goal { get; set; }
        public float identity_0_0 { get; set; }
        public float identity_0_1 { get; set; }
        public float identity_0_2 { get; set; }
        public float identity_0_3 { get; set; }
        public float identity_0_4 { get; set; }
        public float identity_0_5 { get; set; }
        public float identity_0_6 { get; set; }
        public float identity_0_7 { get; set; }
        public float identity_0_8 { get; set; }
        public float identity_1_1 { get; set; }
        public float identity_1_2 { get; set; }
        public float identity_1_3 { get; set; }
        public float identity_1_4 { get; set; }
        public float identity_1_5 { get; set; }
        public float identity_1_6 { get; set; }
        public float identity_1_7 { get; set; }
        public float identity_1_8 { get; set; }
        public float identity_0_over8 { get; set; }
        public float identity_1_over8 { get; set; }
        public float identity_2_2 { get; set; }
        public float identity_2_3 { get; set; }
        public float identity_2_4 { get; set; }
        public float identity_2_5 { get; set; }
        public float identity_2_6 { get; set; }
        public float identity_2_7 { get; set; }
        public float identity_2_8 { get; set; }
        public float identity_2_over8 { get; set; }
        public float identity_3_3 { get; set; }
        public float identity_3_4 { get; set; }
        public float identity_3_5 { get; set; }
        public float identity_3_6 { get; set; }
        public float identity_3_7 { get; set; }
        public float identity_3_8 { get; set; }
        public float identity_3_over8 { get; set; }
        public float identity_4_4 { get; set; }
        public float identity_4_5 { get; set; }
        public float identity_4_6 { get; set; }
        public float identity_4_7 { get; set; }
        public float identity_4_8 { get; set; }
        public float identity_4_over8 { get; set; }
        public float identity_5_5 { get; set; }
        public float identity_5_6 { get; set; }
        public float identity_5_7 { get; set; }
        public float identity_5_8 { get; set; }
        public float identity_5_over8 { get; set; }
        public float identity_6_6 { get; set; }
        public float identity_6_7 { get; set; }
        public float identity_6_8 { get; set; }
        public float identity_6_over8 { get; set; }
        public float identity_7_7 { get; set; }
        public float identity_7_8 { get; set; }
        public float identity_7_over8 { get; set; }
        public float identity_8_8 { get; set; }
        public float identity_over8_over8 { get; set; }
        public float dangerous_attacks_minute_ratio { get; set; }
        public float home_dangerous_attacks_minute_ratio { get; set; }
        public float away_dangerous_attacks_minute_ratio { get; set; }
        public float dangerous_attacks_ratio { get; set; }
        public float home_dangerous_attacks_ratio { get; set; }
        public float away_dangerous_attacks_ratio { get; set; }
        public bool is_second_half { get; set; }
        public float goal_diff { get; set; }
        public float time_2 { get; set; }
        public float time_log { get; set; }
        public float time_3 { get; set; }
        public float total_attacks_ratio_log { get; set; }
        public float total_attacks_ratio_2 { get; set; }
        public float home_attacks_ratio_log { get; set; }
        public float home_attacks_ratio_2 { get; set; }
        public float away_attacks_ratio_log { get; set; }
        public float away_attacks_ratio_2 { get; set; }
        public float total_penalties_ratio_log { get; set; }
        public float total_penalties_ratio_2 { get; set; }
        public float home_penalties_ratio_log { get; set; }
        public float home_penalties_ratio_2 { get; set; }
        public float away_penalties_ratio_log { get; set; }
        public float away_penalties_ratio_2 { get; set; }
        public float total_corners_ratio_log { get; set; }
        public float total_corners_ratio_2 { get; set; }
        public float home_corners_ratio_log { get; set; }
        public float home_corners_ratio_2 { get; set; }
        public float away_corners_ratio_log { get; set; }
        public float away_corners_ratio_2 { get; set; }
        public float dangerous_attacks_minute_ratio_log { get; set; }
        public float dangerous_attacks_minute_ratio_2 { get; set; }
        public float home_dangerous_attacks_minute_ratio_log { get; set; }
        public float home_dangerous_attacks_minute_ratio_2 { get; set; }
        public float away_dangerous_attacks_minute_ratio_log { get; set; }
        public float away_dangerous_attacks_minute_ratio_2 { get; set; }
        public float dangerous_attacks_ratio_log { get; set; }
        public float dangerous_attacks_ratio_2 { get; set; }
        public float home_dangerous_attacks_ratio_log { get; set; }
        public float home_dangerous_attacks_ratio_2 { get; set; }
        public float goal_diff_log { get; set; }
        public float goal_diff_2 { get; set; }

    }
}
