// <auto-generated />
using System;
using InPlayWiseData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InPlayWise.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240101092517_liveMatch1455")]
    partial class liveMatch1455
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InPlayWise.Common.DTO.PredictionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("AwayAttacks")
                        .HasColumnType("smallint");

                    b.Property<short>("AwayCorners")
                        .HasColumnType("smallint");

                    b.Property<short>("AwayDangerousAttacks")
                        .HasColumnType("smallint");

                    b.Property<short>("AwayGoals")
                        .HasColumnType("smallint");

                    b.Property<short>("AwayOwnGoals")
                        .HasColumnType("smallint");

                    b.Property<short>("AwayPenalties")
                        .HasColumnType("smallint");

                    b.Property<short>("AwayPossession")
                        .HasColumnType("smallint");

                    b.Property<short>("AwayRed")
                        .HasColumnType("smallint");

                    b.Property<short>("AwayShotsOffTarget")
                        .HasColumnType("smallint");

                    b.Property<short>("AwayShotsOnTarget")
                        .HasColumnType("smallint");

                    b.Property<short>("AwayYellow")
                        .HasColumnType("smallint");

                    b.Property<short>("ExtraTime")
                        .HasColumnType("smallint");

                    b.Property<short>("HomeAttacks")
                        .HasColumnType("smallint");

                    b.Property<short>("HomeCorners")
                        .HasColumnType("smallint");

                    b.Property<short>("HomeDangerousAttacks")
                        .HasColumnType("smallint");

                    b.Property<short>("HomeGoals")
                        .HasColumnType("smallint");

                    b.Property<short>("HomeOwnGoals")
                        .HasColumnType("smallint");

                    b.Property<short>("HomePenalties")
                        .HasColumnType("smallint");

                    b.Property<short>("HomePossession")
                        .HasColumnType("smallint");

                    b.Property<short>("HomeRed")
                        .HasColumnType("smallint");

                    b.Property<short>("HomeShotsOffTarget")
                        .HasColumnType("smallint");

                    b.Property<short>("HomeShotsOnTarget")
                        .HasColumnType("smallint");

                    b.Property<short>("HomeYellow")
                        .HasColumnType("smallint");

                    b.Property<short>("Incident")
                        .HasColumnType("smallint");

                    b.Property<string>("MatchId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("MatchMinutes")
                        .HasColumnType("smallint");

                    b.Property<short>("MatchStatus")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("PredictionData");
                });

            modelBuilder.Entity("InPlayWise.Common.SportsEntities.RecentMatchModel", b =>
                {
                    b.Property<string>("MatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AwayAttacks")
                        .HasColumnType("int");

                    b.Property<string>("AwayCornerMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AwayCorners")
                        .HasColumnType("int");

                    b.Property<int>("AwayDangerousAttacks")
                        .HasColumnType("int");

                    b.Property<string>("AwayGoalMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AwayGoals")
                        .HasColumnType("int");

                    b.Property<short>("AwayOwnGoals")
                        .HasColumnType("smallint");

                    b.Property<short>("AwayPenalties")
                        .HasColumnType("smallint");

                    b.Property<int>("AwayPossession")
                        .HasColumnType("int");

                    b.Property<int>("AwayRedCards")
                        .HasColumnType("int");

                    b.Property<string>("AwayRedMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwayShotsMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AwayShotsOffTarget")
                        .HasColumnType("int");

                    b.Property<int>("AwayShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<string>("AwayShotsOnTargetMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwaySubstitutionMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwayTeamId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwayTeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwayYellowMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AwayYellowRedCards")
                        .HasColumnType("int");

                    b.Property<string>("CompetitionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompetitionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GameDrawn")
                        .HasColumnType("bit");

                    b.Property<int>("HomeAttacks")
                        .HasColumnType("int");

                    b.Property<string>("HomeCornerMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HomeCorners")
                        .HasColumnType("int");

                    b.Property<int>("HomeDangerousAttacks")
                        .HasColumnType("int");

                    b.Property<string>("HomeGoalMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HomeGoals")
                        .HasColumnType("int");

                    b.Property<short>("HomeOwnGoals")
                        .HasColumnType("smallint");

                    b.Property<short>("HomePenalties")
                        .HasColumnType("smallint");

                    b.Property<int>("HomePossession")
                        .HasColumnType("int");

                    b.Property<int>("HomeRedCards")
                        .HasColumnType("int");

                    b.Property<string>("HomeRedMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeShotsMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HomeShotsOffTarget")
                        .HasColumnType("int");

                    b.Property<int>("HomeShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<string>("HomeShotsOnTargetMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeSubstitutionMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeTeamId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeTeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HomeWin")
                        .HasColumnType("bit");

                    b.Property<int>("HomeYellowCards")
                        .HasColumnType("int");

                    b.Property<string>("HomeYellowMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MatchStartTime")
                        .HasColumnType("bigint");

                    b.Property<string>("SeasonId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MatchId");

                    b.ToTable("RecentMatches");
                });

            modelBuilder.Entity("InPlayWise.Common.SportsEntities.TeamModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompetitionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsNational")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Country")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ThemeIsDark")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.FavouriteCompetitions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompetitionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("UserId");

                    b.ToTable("FavouriteCompetitions");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.FavouriteTeams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeamId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("FavouriteTeams");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.FeaturesCountEntities.FeatureCounter", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.ToTable("FeatureCounters");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.FeaturesCountEntities.LiveInsightsPerGameCounter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ApiHits")
                        .HasColumnType("int");

                    b.Property<string>("FeatureCounterUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatchId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureCounterUserId");

                    b.HasIndex("MatchId");

                    b.ToTable("LiveInsightsPerGameCounters");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.MatchAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("AlertBeforeInMinutes")
                        .HasColumnType("smallint");

                    b.Property<string>("MatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("MatchTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId");

                    b.ToTable("MatchAlerts");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.MatchStatus", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MatchStates");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.MembershipEntities.Features", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccumulatorGenerators")
                        .HasColumnType("int");

                    b.Property<int>("CleverLabelling")
                        .HasColumnType("int");

                    b.Property<int>("HistoryOfAccumulators")
                        .HasColumnType("int");

                    b.Property<int>("LeagueStatistics")
                        .HasColumnType("int");

                    b.Property<int>("LiveInsightPerGame")
                        .HasColumnType("int");

                    b.Property<int>("LivePredictionPerGAme")
                        .HasColumnType("int");

                    b.Property<int>("MaxPredictions")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ShockDetectors")
                        .HasColumnType("int");

                    b.Property<int>("WiseProHedge")
                        .HasColumnType("int");

                    b.Property<bool>("WiseProIncluded")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("PlanFeatures");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.MembershipEntities.Price", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IntervalInDays")
                        .HasColumnType("int");

                    b.Property<int>("PriceInCents")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StripeId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.MembershipEntities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.MembershipEntities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SubscriptionEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SubscriptionStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.Opportunities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AwayTeamFirstHalfWin")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamSecondHalfWin")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamWin")
                        .HasColumnType("int");

                    b.Property<int>("BTTS")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamSecondHalfWin")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamWin")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamWinFirstHalfWin")
                        .HasColumnType("int");

                    b.Property<string>("MatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OverEightPointFiveCorners")
                        .HasColumnType("int");

                    b.Property<int>("OverEightPointFiveGoals")
                        .HasColumnType("int");

                    b.Property<int>("OverFivePointFiveCorners")
                        .HasColumnType("int");

                    b.Property<int>("OverFivePointFiveGoals")
                        .HasColumnType("int");

                    b.Property<int>("OverFourPointFiveCorners")
                        .HasColumnType("int");

                    b.Property<int>("OverFourPointFiveGoals")
                        .HasColumnType("int");

                    b.Property<int>("OverNinePointFiveCorners")
                        .HasColumnType("int");

                    b.Property<int>("OverNinePointFiveGoals")
                        .HasColumnType("int");

                    b.Property<int>("OverOnePointFiveCorners")
                        .HasColumnType("int");

                    b.Property<int>("OverOnePointFiveGoals")
                        .HasColumnType("int");

                    b.Property<int>("OverSevenPointFiveCorners")
                        .HasColumnType("int");

                    b.Property<int>("OverSevenPointFiveGoals")
                        .HasColumnType("int");

                    b.Property<int>("OverSixPointFiveCorners")
                        .HasColumnType("int");

                    b.Property<int>("OverSixPointFiveGoals")
                        .HasColumnType("int");

                    b.Property<int>("OverThreePointFiveCorners")
                        .HasColumnType("int");

                    b.Property<int>("OverThreePointFiveGoals")
                        .HasColumnType("int");

                    b.Property<int>("OverTwoPointFiveCorners")
                        .HasColumnType("int");

                    b.Property<int>("OverTwoPointFiveGoals")
                        .HasColumnType("int");

                    b.Property<int>("OverZeroPointFiveCorners")
                        .HasColumnType("int");

                    b.Property<int>("OverZeroPointFiveGoals")
                        .HasColumnType("int");

                    b.Property<int>("UnderEightPointFiveCorners")
                        .HasColumnType("int");

                    b.Property<int>("UnderEightPointFiveGoals")
                        .HasColumnType("int");

                    b.Property<int>("UnderFivePointFiveCorners")
                        .HasColumnType("int");

                    b.Property<int>("UnderFivePointFiveGoals")
                        .HasColumnType("int");

                    b.Property<int>("UnderFourPointFiveCorners")
                        .HasColumnType("int");

                    b.Property<int>("UnderFourPointFiveGoals")
                        .HasColumnType("int");

                    b.Property<int>("UnderNinePointFiveCorners")
                        .HasColumnType("int");

                    b.Property<int>("UnderNinePointFiveGoals")
                        .HasColumnType("int");

                    b.Property<int>("UnderOnePointFiveCorners")
                        .HasColumnType("int");

                    b.Property<int>("UnderOnePointFiveGoals")
                        .HasColumnType("int");

                    b.Property<int>("UnderSevenPointFiveCorners")
                        .HasColumnType("int");

                    b.Property<int>("UnderSevenPointFiveGoals")
                        .HasColumnType("int");

                    b.Property<int>("UnderSixPointFiveCorners")
                        .HasColumnType("int");

                    b.Property<int>("UnderSixPointFiveGoals")
                        .HasColumnType("int");

                    b.Property<int>("UnderThreePointFiveCorners")
                        .HasColumnType("int");

                    b.Property<int>("UnderThreePointFiveGoals")
                        .HasColumnType("int");

                    b.Property<int>("UnderTwoPointFiveCorners")
                        .HasColumnType("int");

                    b.Property<int>("UnderTwoPointFiveGoals")
                        .HasColumnType("int");

                    b.Property<int>("UnderZeroPointFiveCorners")
                        .HasColumnType("int");

                    b.Property<int>("UnderZeroPointFiveGoals")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique()
                        .HasFilter("[MatchId] IS NOT NULL");

                    b.ToTable("OpportunitiesAll");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Odds")
                        .HasColumnType("real");

                    b.Property<int>("Prediction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Opportunities");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.ResetPasswordModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResetPassword");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.SportsEntities.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.SportsEntities.Competition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("int");

                    b.Property<string>("CurrentSeasonId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeagueLevel")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRounds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.SportsEntities.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.SportsEntities.Season", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompetitionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EndTime")
                        .HasColumnType("bigint");

                    b.Property<bool>("HasPlayerStats")
                        .HasColumnType("bit");

                    b.Property<bool>("HasTeamStats")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<long>("StartTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.SportsEntities.Team", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompetitionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FoundationTime")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsNational")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.SportsEntities.UpcomingMatch", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AwayTeamId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompetitionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HomeTeamId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SeasonId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("UpcomingMatches");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.UserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ThemeDark")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("InPlayWise.Data.SportsEntities.LiveMatchModel", b =>
                {
                    b.Property<string>("MatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<short>("AwayAttacks")
                        .HasColumnType("smallint");

                    b.Property<string>("AwayCornerMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("AwayCorners")
                        .HasColumnType("smallint");

                    b.Property<short>("AwayDangerousAttacks")
                        .HasColumnType("smallint");

                    b.Property<string>("AwayGoalMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("AwayGoals")
                        .HasColumnType("smallint");

                    b.Property<short>("AwayOwnGoals")
                        .HasColumnType("smallint");

                    b.Property<short>("AwayPenalties")
                        .HasColumnType("smallint");

                    b.Property<short>("AwayPossession")
                        .HasColumnType("smallint");

                    b.Property<short>("AwayRed")
                        .HasColumnType("smallint");

                    b.Property<string>("AwayRedMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwayShotsMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("AwayShotsOffTarget")
                        .HasColumnType("smallint");

                    b.Property<short>("AwayShotsOnTarget")
                        .HasColumnType("smallint");

                    b.Property<string>("AwayShotsOnTargetMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwaySubstitutionMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwayTeamId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwayTeamLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwayTeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwayTeamShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("AwayYellow")
                        .HasColumnType("smallint");

                    b.Property<string>("AwayYellowMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompetitionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompetitionLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompetitionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompetitionShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CurrentKickoffTime")
                        .HasColumnType("bigint");

                    b.Property<bool>("Ended")
                        .HasColumnType("bit");

                    b.Property<bool>("EndedAbruptly")
                        .HasColumnType("bit");

                    b.Property<bool>("ExtraPenalties")
                        .HasColumnType("bit");

                    b.Property<bool>("ExtraTime")
                        .HasColumnType("bit");

                    b.Property<short>("HomeAttacks")
                        .HasColumnType("smallint");

                    b.Property<string>("HomeCornerMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("HomeCorners")
                        .HasColumnType("smallint");

                    b.Property<short>("HomeDangerousAttacks")
                        .HasColumnType("smallint");

                    b.Property<string>("HomeGoalMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("HomeGoals")
                        .HasColumnType("smallint");

                    b.Property<short>("HomeOwnGoals")
                        .HasColumnType("smallint");

                    b.Property<short>("HomePenalties")
                        .HasColumnType("smallint");

                    b.Property<short>("HomePossession")
                        .HasColumnType("smallint");

                    b.Property<short>("HomeRed")
                        .HasColumnType("smallint");

                    b.Property<string>("HomeRedMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeShotsMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("HomeShotsOffTarget")
                        .HasColumnType("smallint");

                    b.Property<short>("HomeShotsOnTarget")
                        .HasColumnType("smallint");

                    b.Property<string>("HomeShotsOnTargetMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeSubstitutionMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeTeamId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeTeamLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeTeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeTeamShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("HomeYellow")
                        .HasColumnType("smallint");

                    b.Property<string>("HomeYellowMinutes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("MatchMinutes")
                        .HasColumnType("smallint");

                    b.Property<long>("MatchStartTime")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("MatchStartTimeFormatted")
                        .HasColumnType("datetime2");

                    b.Property<short>("MatchStatus")
                        .HasColumnType("smallint");

                    b.Property<long>("MatchTimeSeconds")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OfficialStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeasonId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("matchEndMinutes")
                        .HasColumnType("int");

                    b.Property<int>("stoppageTime")
                        .HasColumnType("int");

                    b.HasKey("MatchId");

                    b.ToTable("LiveMatches");
                });

            modelBuilder.Entity("InPlayWiseData.Entities.EventModel", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventGround")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.FavouriteCompetitions", b =>
                {
                    b.HasOne("InPlayWise.Data.Entities.SportsEntities.Competition", "Competition")
                        .WithMany("favComps")
                        .HasForeignKey("CompetitionId");

                    b.HasOne("InPlayWise.Data.Entities.ApplicationUser", "User")
                        .WithMany("FavouriteCompetition")
                        .HasForeignKey("UserId");

                    b.Navigation("Competition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.FavouriteTeams", b =>
                {
                    b.HasOne("InPlayWise.Data.Entities.SportsEntities.Team", "Teams")
                        .WithMany("FavTeams")
                        .HasForeignKey("TeamId");

                    b.HasOne("InPlayWise.Data.Entities.ApplicationUser", "User")
                        .WithMany("FavouriteTeams")
                        .HasForeignKey("UserId");

                    b.Navigation("Teams");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.FeaturesCountEntities.FeatureCounter", b =>
                {
                    b.HasOne("InPlayWise.Data.Entities.UserProfile", "UserProfile")
                        .WithOne("Features")
                        .HasForeignKey("InPlayWise.Data.Entities.FeaturesCountEntities.FeatureCounter", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.FeaturesCountEntities.LiveInsightsPerGameCounter", b =>
                {
                    b.HasOne("InPlayWise.Data.Entities.FeaturesCountEntities.FeatureCounter", "FeatureCounter")
                        .WithMany("LiveInsightsPerGame")
                        .HasForeignKey("FeatureCounterUserId");

                    b.HasOne("InPlayWise.Data.SportsEntities.LiveMatchModel", "Match")
                        .WithMany("LiveInsightsCounter")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("FeatureCounter");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.MatchAlert", b =>
                {
                    b.HasOne("InPlayWise.Data.Entities.SportsEntities.UpcomingMatch", "UpcomingMatch")
                        .WithMany("MatchAlerts")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InPlayWise.Data.Entities.ApplicationUser", "User")
                        .WithMany("MatchAlerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("UpcomingMatch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.MembershipEntities.Features", b =>
                {
                    b.HasOne("InPlayWise.Data.Entities.MembershipEntities.Product", "Product")
                        .WithOne("Features")
                        .HasForeignKey("InPlayWise.Data.Entities.MembershipEntities.Features", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.MembershipEntities.Price", b =>
                {
                    b.HasOne("InPlayWise.Data.Entities.MembershipEntities.Product", "Product")
                        .WithMany("Price")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.MembershipEntities.Subscription", b =>
                {
                    b.HasOne("InPlayWise.Data.Entities.MembershipEntities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InPlayWise.Data.Entities.ApplicationUser", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("InPlayWise.Data.Entities.MembershipEntities.Subscription", "UserId");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.Opportunities", b =>
                {
                    b.HasOne("InPlayWise.Data.SportsEntities.LiveMatchModel", "Match")
                        .WithOne("OpportunitiesAll")
                        .HasForeignKey("InPlayWise.Data.Entities.Opportunities", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Match");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.Opportunity", b =>
                {
                    b.HasOne("InPlayWise.Data.SportsEntities.LiveMatchModel", "Match")
                        .WithMany("Opportunities")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Match");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.SportsEntities.UpcomingMatch", b =>
                {
                    b.HasOne("InPlayWise.Data.Entities.SportsEntities.Team", "AwayTeam")
                        .WithMany("UpcomingAwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InPlayWise.Data.Entities.SportsEntities.Competition", "Competition")
                        .WithMany("UpcomingMatches")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InPlayWise.Data.Entities.SportsEntities.Team", "HomeTeam")
                        .WithMany("UpcomingHomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AwayTeam");

                    b.Navigation("Competition");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.UserProfile", b =>
                {
                    b.HasOne("InPlayWise.Data.Entities.ApplicationUser", "User")
                        .WithOne("Profile")
                        .HasForeignKey("InPlayWise.Data.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InPlayWise.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InPlayWise.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InPlayWise.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InPlayWise.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("FavouriteCompetition");

                    b.Navigation("FavouriteTeams");

                    b.Navigation("MatchAlerts");

                    b.Navigation("Profile");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.FeaturesCountEntities.FeatureCounter", b =>
                {
                    b.Navigation("LiveInsightsPerGame");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.MembershipEntities.Product", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.SportsEntities.Competition", b =>
                {
                    b.Navigation("UpcomingMatches");

                    b.Navigation("favComps");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.SportsEntities.Team", b =>
                {
                    b.Navigation("FavTeams");

                    b.Navigation("UpcomingAwayMatches");

                    b.Navigation("UpcomingHomeMatches");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.SportsEntities.UpcomingMatch", b =>
                {
                    b.Navigation("MatchAlerts");
                });

            modelBuilder.Entity("InPlayWise.Data.Entities.UserProfile", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("InPlayWise.Data.SportsEntities.LiveMatchModel", b =>
                {
                    b.Navigation("LiveInsightsCounter");

                    b.Navigation("Opportunities");

                    b.Navigation("OpportunitiesAll");
                });
#pragma warning restore 612, 618
        }
    }
}
