//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAASCLOUDAPP.BusinessLayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAASCLOUDAPP.BusinessLayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       
        ///        	   
        ///        &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;	
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;/&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///&lt;title&gt;Email Template&lt;/title&gt;
        ///&lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot; &gt;
        ///&lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ActionAndSolutionBody {
            get {
                return ResourceManager.GetString("ActionAndSolutionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action And Solution Details.
        /// </summary>
        public static string ActionAndSolutionSubject {
            get {
                return ResourceManager.GetString("ActionAndSolutionSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;/&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///&lt;title&gt;Email Template&lt;/title&gt;
        ///&lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot; &gt;
        ///&lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///	&lt;tbody&gt;
        ///		&lt;tr&gt;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ActionsDueInNextOneDayBody {
            get {
                return ResourceManager.GetString("ActionsDueInNextOneDayBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action(s) due in 1 day.
        /// </summary>
        public static string ActionsDueInNextOneDaySubject {
            get {
                return ResourceManager.GetString("ActionsDueInNextOneDaySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///         &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;/&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///&lt;title&gt;Email Template&lt;/title&gt;
        ///&lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot; &gt;
        ///&lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///	&lt;tbody&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ActionsDueInNextTwoDaysBody {
            get {
                return ResourceManager.GetString("ActionsDueInNextTwoDaysBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action(s) due in 2 days.
        /// </summary>
        public static string ActionsDueInNextTwoDaysSubject {
            get {
                return ResourceManager.GetString("ActionsDueInNextTwoDaysSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string AddedString {
            get {
                return ResourceManager.GetString("AddedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot;&gt;
        ///    &lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AddNewIssueBody {
            get {
                return ResourceManager.GetString("AddNewIssueBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New issue added.
        /// </summary>
        public static string AddNewIssueSubject {
            get {
                return ResourceManager.GetString("AddNewIssueSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;/&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///&lt;title&gt;Email Template&lt;/title&gt;
        ///&lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot; &gt;
        ///&lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///	&lt;tbody&gt;
        ///		&lt;tr&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AddNewPartnerInstanceBody {
            get {
                return ResourceManager.GetString("AddNewPartnerInstanceBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Workfacta partner account is ready..
        /// </summary>
        public static string AddNewPartnerInstanceSubject {
            get {
                return ResourceManager.GetString("AddNewPartnerInstanceSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///          &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;/&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///&lt;title&gt;Email Template&lt;/title&gt;
        ///&lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot; &gt;
        ///&lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///	&lt;tbody&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AddNewSuggestionBody {
            get {
                return ResourceManager.GetString("AddNewSuggestionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workfacta - You have a new suggestion..
        /// </summary>
        public static string AddNewSuggestionSubject {
            get {
                return ResourceManager.GetString("AddNewSuggestionSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot;&gt;
        ///    &lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AddUpdateMultipleIssuesBody {
            get {
                return ResourceManager.GetString("AddUpdateMultipleIssuesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New issue added.
        /// </summary>
        public static string AddUpdateMultipleIssuesSubject {
            get {
                return ResourceManager.GetString("AddUpdateMultipleIssuesSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///          &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;/&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///&lt;title&gt;Email Template&lt;/title&gt;
        ///&lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot; &gt;
        ///&lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///	&lt;tbody&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AppUpdateNotificationBody {
            get {
                return ResourceManager.GetString("AppUpdateNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated App Notification.
        /// </summary>
        public static string AppUpdateNotificationSubject {
            get {
                return ResourceManager.GetString("AppUpdateNotificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string AverageString {
            get {
                return ResourceManager.GetString("AverageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Solved.
        /// </summary>
        public static string ChallengeSolvedSubject {
            get {
                return ResourceManager.GetString("ChallengeSolvedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenges.
        /// </summary>
        public static string ChallengesString {
            get {
                return ResourceManager.GetString("ChallengesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge.
        /// </summary>
        public static string ChallengeString {
            get {
                return ResourceManager.GetString("ChallengeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Updated.
        /// </summary>
        public static string ChallengeUpdatedSubject {
            get {
                return ResourceManager.GetString("ChallengeUpdatedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string CreatedString {
            get {
                return ResourceManager.GetString("CreatedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion Solved.
        /// </summary>
        public static string DiscussionSolvedSubject {
            get {
                return ResourceManager.GetString("DiscussionSolvedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussions.
        /// </summary>
        public static string DiscussionsString {
            get {
                return ResourceManager.GetString("DiscussionsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion.
        /// </summary>
        public static string DiscussionString {
            get {
                return ResourceManager.GetString("DiscussionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion Updated.
        /// </summary>
        public static string DiscussionUpdatedSubject {
            get {
                return ResourceManager.GetString("DiscussionUpdatedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            &lt;html&gt;
        ///            &lt;body&gt;
        ///            &lt;div&gt; 
        ///            &lt;div&gt;
        ///             &lt;table style=&quot;width: 100%;&quot;&gt;
        ///             &lt;tr&gt;
        ///             &lt;th&gt;
        ///             &lt;img src=&quot;https://assets.workfacta.com/emails/2021-05/WorkfactaFullLogo.png&quot;  alt=&quot;Workfacta logo&quot; width=&quot;100%&quot; height=&quot;100&quot;/&gt;
        ///             &lt;/th&gt;
        ///             &lt;/tr&gt;
        ///             &lt;tr&gt;
        ///                 &lt;th style=&quot;width: 65%;text-align:left;&quot;&gt;
        ///                     &lt;h2 style=&quot;display: inline-block;margin: 0;&quot;&gt;
        ///                        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string emailconfirmationBody {
            get {
                return ResourceManager.GetString("emailconfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workfacta Email Confirmation.
        /// </summary>
        public static string EmailConfirmationSubject {
            get {
                return ResourceManager.GetString("EmailConfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunities, Challenges and Discussions.
        /// </summary>
        public static string GenericIssuesString {
            get {
                return ResourceManager.GetString("GenericIssuesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunities, Challenges and Discussions Updated.
        /// </summary>
        public static string GenericIssueUpdatedSubject {
            get {
                return ResourceManager.GetString("GenericIssueUpdatedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  
        ///    &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;/&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///&lt;title&gt;Email Template&lt;/title&gt;
        ///&lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#f8f8f8;&quot; &gt;
        ///&lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///	&lt;tbody&gt;
        ///		&lt;t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InfoGramTemplateBody {
            get {
                return ResourceManager.GetString("InfoGramTemplateBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Planning - Summary.
        /// </summary>
        public static string InfoGramTemplateSubject {
            get {
                return ResourceManager.GetString("InfoGramTemplateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;/&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///&lt;title&gt;Email Template&lt;/title&gt;
        ///&lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot; &gt;
        ///&lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///	&lt;tbody&gt;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InviteUserBody {
            get {
                return ResourceManager.GetString("InviteUserBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workfacta Invitation.
        /// </summary>
        public static string InviteUserSubject {
            get {
                return ResourceManager.GetString("InviteUserSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;/&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///&lt;title&gt;Email Template&lt;/title&gt;
        ///&lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot; &gt;
        ///&lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///	&lt;tbody&gt;
        ///		&lt;tr&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InviteUserWithResetPasswordLinkBody {
            get {
                return ResourceManager.GetString("InviteUserWithResetPasswordLinkBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Workfacta account is ready..
        /// </summary>
        public static string InviteUserWithResetPasswordLinkSubject {
            get {
                return ResourceManager.GetString("InviteUserWithResetPasswordLinkSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot;&gt;
        ///    &lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ManagementNotificationLateUpdatesBody {
            get {
                return ResourceManager.GetString("ManagementNotificationLateUpdatesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot;&gt;
        ///    &lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ManagementNotificationLateUpdatesLineManagerBody {
            get {
                return ResourceManager.GetString("ManagementNotificationLateUpdatesLineManagerBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Notification Late Updates.
        /// </summary>
        public static string ManagementNotificationLateUpdatesSubject {
            get {
                return ResourceManager.GetString("ManagementNotificationLateUpdatesSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot;&gt;
        ///    &lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MeetingCancelEmailBody {
            get {
                return ResourceManager.GetString("MeetingCancelEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Cancelled.
        /// </summary>
        public static string MeetingCancelEmailSubject {
            get {
                return ResourceManager.GetString("MeetingCancelEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot;&gt;
        ///    &lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MeetingPostponeEmailBody {
            get {
                return ResourceManager.GetString("MeetingPostponeEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Moved.
        /// </summary>
        public static string MeetingPostponeEmailSubject {
            get {
                return ResourceManager.GetString("MeetingPostponeEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot;&gt;
        ///    &lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MeetingRemindersWithOverduesBody {
            get {
                return ResourceManager.GetString("MeetingRemindersWithOverduesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue Update Reminder.
        /// </summary>
        public static string MeetingRemindersWithOverduesSubject {
            get {
                return ResourceManager.GetString("MeetingRemindersWithOverduesSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot;&gt;
        ///    &lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MeetingUpdateReminderBody {
            get {
                return ResourceManager.GetString("MeetingUpdateReminderBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Reminder.
        /// </summary>
        public static string MeetingUpdateReminderSubject {
            get {
                return ResourceManager.GetString("MeetingUpdateReminderSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot;&gt;
        ///    &lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial;box-sizing: border-box;&quot; cellp [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MinutesOfMeetingEmailBody {
            get {
                return ResourceManager.GetString("MinutesOfMeetingEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes Of Meeting.
        /// </summary>
        public static string MinutesOfMeetingEmailSubject {
            get {
                return ResourceManager.GetString("MinutesOfMeetingEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///           &lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///      @media only screen and (max-width: 480px) {
        ///        table#canspamBar td {
        ///          font-size:14px !important;
        ///        }
        ///        
        ///        table#canspamBar td a {
        ///          display:block !important;
        ///          margin-top:10px !important;
        ///        }
        ///      }
        ///    &lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, ma [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MondayNonUpdatedReminderBody {
            get {
                return ResourceManager.GetString("MondayNonUpdatedReminderBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding Non-Updated Data.
        /// </summary>
        public static string MondayNonUpdatedReminderSubject {
            get {
                return ResourceManager.GetString("MondayNonUpdatedReminderSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;/&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///&lt;title&gt;Email Template&lt;/title&gt;
        ///&lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot; &gt;
        ///&lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///	&lt;tbody&gt;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MultipleActionAddUpdateBody {
            get {
                return ResourceManager.GetString("MultipleActionAddUpdateBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New action added updated.
        /// </summary>
        public static string MultipleActionAddUpdateSubject {
            get {
                return ResourceManager.GetString("MultipleActionAddUpdateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;/&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///&lt;title&gt;Email Template&lt;/title&gt;
        ///&lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot; &gt;
        ///&lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///	&lt;tbody&gt;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NewActionAddUpdateBody {
            get {
                return ResourceManager.GetString("NewActionAddUpdateBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New action added updated.
        /// </summary>
        public static string NewActionAddUpdateSubject {
            get {
                return ResourceManager.GetString("NewActionAddUpdateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Challenge created.
        /// </summary>
        public static string NewChallengeCreatedSubject {
            get {
                return ResourceManager.GetString("NewChallengeCreatedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Discussion Created.
        /// </summary>
        public static string NewDiscussionCreatedSubject {
            get {
                return ResourceManager.GetString("NewDiscussionCreatedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Opportunities, Challenges and Discussions Created.
        /// </summary>
        public static string NewGenericIssueCreatedSubject {
            get {
                return ResourceManager.GetString("NewGenericIssueCreatedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Opportunity created.
        /// </summary>
        public static string NewOpportunityCreatedSubject {
            get {
                return ResourceManager.GetString("NewOpportunityCreatedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot;&gt;
        ///    &lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NewsEmail {
            get {
                return ResourceManager.GetString("NewsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunities.
        /// </summary>
        public static string OpportunitiesString {
            get {
                return ResourceManager.GetString("OpportunitiesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot;&gt;
        ///    &lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OpportunityChallengeSolvedBody {
            get {
                return ResourceManager.GetString("OpportunityChallengeSolvedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Solved.
        /// </summary>
        public static string OpportunitySolvedSubject {
            get {
                return ResourceManager.GetString("OpportunitySolvedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity.
        /// </summary>
        public static string OpportunityString {
            get {
                return ResourceManager.GetString("OpportunityString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Updated.
        /// </summary>
        public static string OpportunityUpdatedSubject {
            get {
                return ResourceManager.GetString("OpportunityUpdatedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot;&gt;
        ///    &lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PaymentSuccessFailedBody {
            get {
                return ResourceManager.GetString("PaymentSuccessFailedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot;&gt;
        ///    &lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PrintMeetingPDFBody {
            get {
                return ResourceManager.GetString("PrintMeetingPDFBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Agenda.
        /// </summary>
        public static string PrintMeetingPDFSubject {
            get {
                return ResourceManager.GetString("PrintMeetingPDFSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot;&gt;
        ///    &lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportUpdatedEmail {
            get {
                return ResourceManager.GetString("ReportUpdatedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;/&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///&lt;title&gt;Email Template&lt;/title&gt;
        ///&lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot; &gt;
        ///&lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///	&lt;tbody&gt;
        ///		&lt;tr&gt;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ResetPasswordBody {
            get {
                return ResourceManager.GetString("ResetPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPasswordSubject {
            get {
                return ResourceManager.GetString("ResetPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string ResultString {
            get {
                return ResourceManager.GetString("ResultString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Update Failed.
        /// </summary>
        public static string SubscriptionUpdateFailedSubject {
            get {
                return ResourceManager.GetString("SubscriptionUpdateFailedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot;&gt;
        ///    &lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SystemEmailBody {
            get {
                return ResourceManager.GetString("SystemEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string TargetString {
            get {
                return ResourceManager.GetString("TargetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string UpdatedString {
            get {
                return ResourceManager.GetString("UpdatedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot;&gt;
        ///    &lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial&quot; cellpadding=&quot;0&quot; cellspacing [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UpdateIssueBody {
            get {
                return ResourceManager.GetString("UpdateIssueBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to issue updated.
        /// </summary>
        public static string UpdateIssueSubject {
            get {
                return ResourceManager.GetString("UpdateIssueSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px; background:#fafafa;&quot;&gt;
        ///    &lt;table style=&quot;width:100%;font-family: &apos;Roboto&apos;, sans-serif, Arial;box-sizing: border-box;&quot; cel [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WeeklyUpdateReportEmailBody {
            get {
                return ResourceManager.GetString("WeeklyUpdateReportEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Update Report.
        /// </summary>
        public static string WeeklyUpdateReportEmailSubject {
            get {
                return ResourceManager.GetString("WeeklyUpdateReportEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string WeekString {
            get {
                return ResourceManager.GetString("WeekString", resourceCulture);
            }
        }
    }
}
